### ISSUE TITLE
Unable to use IPv6-only hosts

### ISSUE THREAD

**Issue by jortgies** [FlxPeters/netbox-prometheus-sd#33]
When a device only has IPv6 configured (as primary address) it gets discarded with the following debug-log:
```
DEBUG:Drop vm 'vela.ortg.de' due to missing primary IPv4
```

Is there any reason why you are using `primary_ip4` instead of `primary_ip` in [`netbox_sd/inventory.py`](https://github.com/FlxPeters/netbox-prometheus-sd/blob/master/netbox_sd/inventory.py#L52)?
I propose a fix in PR #32. This should also work for any Netbox device/vm which only has an IPv4 address configured.

**Comment by FlxPeters** [comment]
The simple reason is, that i do not have any IPv6 device now. That's a valid point, i will check the PR soon and merge afterwards. Thanks for your contribution!

**Comment by FlxPeters** [comment]
I released a 0.0.3-rc1 to test this. Feel free to give a feedback if it works for you.

**Comment by jortgies** [comment]
Thanks for taking care so quickly!
I can confirm that the new version works for me. All devices get added, as expected.
