### ISSUE TITLE
Add meta labels with custom fields

### ISSUE THREAD

**Issue by gillg** [FlxPeters/netbox-prometheus-sd#80]
A great improvement could be to add all the custom fields as meta labels.

Exemple : 
```
__meta_netbox_cf_myfield1 = "xxxx"
__meta_netbox_cf_myfield2 = "xxxx"
```

If the underlying field is an object, exposing the name and slug is needed
Exemple with a custom field of type "Location" :
```
__meta_netbox_cf_myfieldlocation_name = "xxxx"
__meta_netbox_cf_myfieldlocation_slug = "xxxx"
```

**Comment by FlxPeters** [comment]
We just added custom fields in one of the last PR. It's released as pre release 0.6.0rc1.

Have you tried this?

**Comment by gillg** [comment]
Awesome!! Not yet, I will.
Is there some requirements? I know netbox changed some important things in recent versions.

**Comment by gillg** [comment]
I close it as related to that discussion https://github.com/FlxPeters/netbox-plugin-prometheus-sd/issues/34
