### ISSUE TITLE
Question: Multiple IPs on one device?

### ISSUE THREAD

**Issue by llamafilm** [FlxPeters/netbox-prometheus-sd#91]
I have some servers with 2 IP addresses, one primary and one for out-of-band management.  I'd like to scrape both IPs with Prometheus using 2 different jobs.  For example, blackbox exporter on the primary, and SNMP on the out-of-band IPMI.  Do you have any thoughts on how to accomplish this?

So far I've been scraping an endpoint like this:
```
http://netbox/api/plugins/prometheus-sd/devices?status=active&cf_prometheus_job=netbox_blackbox_ping
```

I could use the `ip-addresses` endpoint instead for the second one, but then I would lose important metadata.  I'm most interested in `site` and `location` labels.

**Comment by FlxPeters** [comment]
Netbox has the ability to map OOB IP next to the primary IP since a while. I think there's already a PR for that which is merged. Does this solve your issue?

It's PR #135 in the plugin repository. This repo is mostly for legacy purposes. I do not develop it actively. But feel free to send s PR.

**Comment by llamafilm** [comment]
Oh ok perfect! I see that now. I accidentally posted in the wrong repo.
